interface Employee {
  id: number
  emp_id: string
  name: string
  position: string
  department: string
  salary: number
  email: string
  join_date: string
}

export const employee: Employee[] = [
  {
    id: 1,
    emp_id: 'EMP001',
    name: 'Andi Saputra',
    position: 'Project Manager',
    department: 'Information Technology',
    salary: 15000000,
    email: 'andi.saputra@example.com',
    join_date: '2020-05-12',
  },
  {
    id: 2,
    emp_id: 'EMP002',
    name: 'Siti Rahmawati',
    position: 'Data Analyst',
    department: 'Information Technology',
    salary: 12000000,
    email: 'siti.rahmawati@example.com',
    join_date: '2021-08-19',
  },
  {
    id: 3,
    emp_id: 'EMP003',
    name: 'Budi Santoso',
    position: 'Accountant',
    department: 'Finance',
    salary: 13000000,
    email: 'budi.santoso@example.com',
    join_date: '2019-11-25',
  },
  {
    id: 4,
    emp_id: 'EMP004',
    name: 'Dewi Lestari',
    position: 'HR Specialist',
    department: 'Human Resources',
    salary: 11000000,
    email: 'dewi.lestari@example.com',
    join_date: '2022-01-15',
  },
  {
    id: 5,
    emp_id: 'EMP005',
    name: 'Rudi Hartono',
    position: 'Software Developer',
    department: 'Information Technology',
    salary: 14000000,
    email: 'rudi.hartono@example.com',
    join_date: '2020-09-30',
  },
  {
    id: 6,
    emp_id: 'EMP006',
    name: 'Indah Permata',
    position: 'Marketing Executive',
    department: 'Marketing',
    salary: 12500000,
    email: 'indah.permata@example.com',
    join_date: '2021-03-22',
  },
  {
    id: 7,
    emp_id: 'EMP007',
    name: 'Agus Prasetyo',
    position: 'Graphic Designer',
    department: 'Creative',
    salary: 10500000,
    email: 'agus.prasetyo@example.com',
    join_date: '2022-07-18',
  },
  {
    id: 8,
    emp_id: 'EMP008',
    name: 'Citra Anggraini',
    position: 'Quality Assurance',
    department: 'Information Technology',
    salary: 11500000,
    email: 'citra.anggraini@example.com',
    join_date: '2020-12-10',
  },
  {
    id: 9,
    emp_id: 'EMP009',
    name: 'Doni Firmansyah',
    position: 'Network Technician',
    department: 'Information Technology',
    salary: 10000000,
    email: 'doni.firmansyah@example.com',
    join_date: '2023-02-05',
  },
  {
    id: 10,
    emp_id: 'EMP010',
    name: 'Lina Kusuma',
    position: 'Secretary',
    department: 'Administration',
    salary: 9500000,
    email: 'lina.kusuma@example.com',
    join_date: '2018-04-14',
  },
  {
    id: 11,
    emp_id: 'EMP011',
    name: 'Fajar Setiawan',
    position: 'Production Supervisor',
    department: 'Production',
    salary: 13500000,
    email: 'fajar.setiawan@example.com',
    join_date: '2019-06-20',
  },
  {
    id: 12,
    emp_id: 'EMP012',
    name: 'Yuni Astuti',
    position: 'Customer Service',
    department: 'Customer Service',
    salary: 9000000,
    email: 'yuni.astuti@example.com',
    join_date: '2021-10-08',
  },
  {
    id: 13,
    emp_id: 'EMP013',
    name: 'Eka Wijaya',
    position: 'Operations Manager',
    department: 'Operations',
    salary: 16000000,
    email: 'eka.wijaya@example.com',
    join_date: '2017-03-17',
  },
  {
    id: 14,
    emp_id: 'EMP014',
    name: 'Rina Handayani',
    position: 'Business Analyst',
    department: 'Strategy',
    salary: 14500000,
    email: 'rina.handayani@example.com',
    join_date: '2020-06-28',
  },
  {
    id: 15,
    emp_id: 'EMP015',
    name: 'Bayu Pratama',
    position: 'Logistics Officer',
    department: 'Logistics',
    salary: 9800000,
    email: 'bayu.pratama@example.com',
    join_date: '2023-01-12',
  },
]
